// ── SCRIPT DE CARGA DE ESPECIFICACIONES (CORREGIDO) ─────────────────────
// Pega esto en la consola del navegador estando en admin.html logueado

(async function() {
  const { initializeApp, getApps } = await import("https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js");
  const { getFirestore, collection, getDocs, setDoc, doc, serverTimestamp } = await import("https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js");

  const firebaseConfig = {
    apiKey: "AIzaSyAGIjtHa251FpHMtF4LW2iD8Yz-JtyB67Y",
    authDomain: "alfredostore-19858.firebaseapp.com",
    projectId: "alfredostore-19858",
    storageBucket: "alfredostore-19858.firebasestorage.app",
    messagingSenderId: "503517454506",
    appId: "1:503517454506:web:7bbfb0f593a379227930d3"
  };

  const app = getApps().length ? getApps()[0] : initializeApp(firebaseConfig);
  const db  = getFirestore(app);

  // Convierte [emoji, label, val] → { e, l, v } para evitar arrays anidados
  function s(e, l, v) { return { e, l, v }; }

  const SPECS_DB = {
    "iPhone 15 Pro Max 256GB eSIM": [
      s("📱","Pantalla","6.7\" LTPO Super Retina XDR OLED (120Hz / 2000 nits)"),
      s("⚙️","Procesador","A17 Pro (3nm)"),
      s("💾","RAM","8GB"),
      s("💾","Almacenamiento","256GB"),
      s("📷","Cámara principal","48MP (OIS) + 12MP (Telefoto 5x) + 12MP (Ultra Gran Angular)"),
      s("📷","Cámara frontal","12MP (TrueDepth)"),
      s("🔋","Batería","4441mAh / Carga rápida 20W"),
      s("🔥","Sistema operativo","iOS 17 (Actualizable a iOS 19+)"),
      s("✅","Lector de Huella","No (Face ID)"),
      s("💦","Resistencia","IP68 (Sumergible hasta 6m por 30 min)"),
      s("✨","Diseño","Titanio de grado aeroespacial / Botón de Acción"),
      s("🌀","Apple Intelligence","Compatible (Beta)"),
    ],
    "iPhone 16 Pro Max 512GB eSIM": [
      s("📱","Pantalla","6.9\" LTPO Super Retina XDR OLED (120Hz / 2000 nits)"),
      s("⚙️","Procesador","A18 Pro (3nm)"),
      s("💾","RAM","8GB"),
      s("💾","Almacenamiento","512GB"),
      s("📷","Cámara principal","48MP (Fusion) + 48MP (Ultra Gran Angular) + 12MP (Telefoto 5x)"),
      s("📷","Cámara frontal","12MP (TrueDepth)"),
      s("🔋","Batería","4685mAh / Carga rápida 30W"),
      s("🔥","Sistema operativo","iOS 18"),
      s("✅","Lector de Huella","No (Face ID)"),
      s("💦","Resistencia","IP68 (Sumergible hasta 6m por 30 min)"),
      s("✨","Diseño","Chasis de Titanio / Control de Cámara (Botón táctil)"),
      s("🌀","Apple Intelligence","Integración nativa avanzada"),
    ],
    "iPhone 17 Pro Max 256GB eSIM": [
      s("📱","Pantalla","6.9\" LTPO Super Retina XDR (120Hz / 2500 nits)"),
      s("⚙️","Procesador","A19 Pro (2nm)"),
      s("💾","RAM","12GB"),
      s("💾","Almacenamiento","256GB"),
      s("📷","Cámara principal","48MP + 48MP (Ultra Gran Angular) + 48MP (Telefoto 5x)"),
      s("📷","Cámara frontal","24MP (TrueDepth)"),
      s("🔋","Batería","4800mAh / Carga rápida 45W"),
      s("🔥","Sistema operativo","iOS 19"),
      s("✅","Lector de Huella","No (Face ID bajo pantalla)"),
      s("💦","Resistencia","IP68 (Sumergible)"),
      s("✨","Diseño","Titanio reforzado / Isla Dinámica reducida"),
      s("🌀","Apple Intelligence","IA Generativa local mejorada"),
    ],
    "iPhone 17 Pro Max 512GB eSIM": [
      s("📱","Pantalla","6.9\" LTPO Super Retina XDR (120Hz / 2500 nits)"),
      s("⚙️","Procesador","A19 Pro (2nm)"),
      s("💾","RAM","12GB"),
      s("💾","Almacenamiento","512GB"),
      s("📷","Cámara principal","48MP + 48MP (Ultra Gran Angular) + 48MP (Telefoto 5x)"),
      s("📷","Cámara frontal","24MP (TrueDepth)"),
      s("🔋","Batería","4800mAh / Carga rápida 45W"),
      s("🔥","Sistema operativo","iOS 19"),
      s("✅","Lector de Huella","No (Face ID bajo pantalla)"),
      s("💦","Resistencia","IP68 (Sumergible)"),
      s("✨","Diseño","Titanio reforzado / Isla Dinámica reducida"),
      s("🌀","Apple Intelligence","IA Generativa local mejorada"),
    ],
    "Galaxy A07 4+128GB": [
      s("📱","Pantalla","6.7\" PLS LCD (60Hz / HD+)"),
      s("⚙️","Procesador","MediaTek Helio G85 (12nm)"),
      s("💾","RAM","4GB"),
      s("💾","Almacenamiento","128GB (Expandible a 1TB)"),
      s("📷","Cámara principal","50MP + 2MP (Sensor de profundidad)"),
      s("📷","Cámara frontal","8MP"),
      s("🔋","Batería","5000mAh / Carga rápida 25W"),
      s("🔥","Sistema operativo","Android 13 (Actualizable a Android 14)"),
      s("✅","Lector de Huella","No posee (Reconocimiento facial)"),
      s("💦","Resistencia","Sin certificación IP"),
      s("✨","Diseño","Acabado con textura lineal"),
      s("🌀","Galaxy AI","No disponible"),
    ],
    "Galaxy A16 4+128GB": [
      s("📱","Pantalla","6.7\" Super AMOLED (90Hz / Full HD+)"),
      s("⚙️","Procesador","Exynos 1330 / Dimensity 6300"),
      s("💾","RAM","4GB"),
      s("💾","Almacenamiento","128GB (Expandible a 1TB)"),
      s("📷","Cámara principal","50MP + 5MP (Ultra Gran Angular) + 2MP (Macro)"),
      s("📷","Cámara frontal","13MP"),
      s("🔋","Batería","5000mAh / Carga rápida 25W"),
      s("🔥","Sistema operativo","Android 14 (6 años de actualizaciones)"),
      s("✅","Lector de Huella","Lateral (En el botón de encendido)"),
      s("💦","Resistencia","IP54 (Polvo y salpicaduras)"),
      s("✨","Diseño","Key Island con acabado brillante"),
      s("🌀","Galaxy AI","No disponible"),
    ],
    "Galaxy A17 4G 4+128GB": [
      s("📱","Pantalla","6.7\" Super AMOLED (90Hz / Full HD+)"),
      s("⚙️","Procesador","MediaTek Helio G99 (6nm)"),
      s("💾","RAM","4GB"),
      s("💾","Almacenamiento","128GB (Expandible a 1TB)"),
      s("📷","Cámara principal","50MP + 5MP (Ultra Gran Angular) + 2MP (Macro)"),
      s("📷","Cámara frontal","13MP"),
      s("🔋","Batería","5000mAh / Carga rápida 25W"),
      s("🔥","Sistema operativo","Android 15 + One UI 7.1"),
      s("✅","Lector de Huella","Lateral"),
      s("💦","Resistencia","IP54"),
      s("✨","Diseño","Key Island con acabado brillante"),
      s("🌀","Galaxy AI","Funciones básicas de edición"),
    ],
    "Galaxy A17 4G 6+128GB": [
      s("📱","Pantalla","6.7\" Super AMOLED (90Hz / Full HD+)"),
      s("⚙️","Procesador","MediaTek Helio G99 (6nm)"),
      s("💾","RAM","6GB"),
      s("💾","Almacenamiento","128GB (Expandible a 1TB)"),
      s("📷","Cámara principal","50MP + 5MP + 2MP (Macro)"),
      s("📷","Cámara frontal","13MP"),
      s("🔋","Batería","5000mAh / Carga rápida 25W"),
      s("🔥","Sistema operativo","Android 15 + One UI 7.1"),
      s("✅","Lector de Huella","Lateral"),
      s("💦","Resistencia","IP54"),
      s("✨","Diseño","Key Island con acabado brillante"),
      s("🌀","Galaxy AI","Funciones básicas de edición"),
    ],
    "Galaxy A17 4G 8+256GB": [
      s("📱","Pantalla","6.7\" Super AMOLED (90Hz / Full HD+)"),
      s("⚙️","Procesador","MediaTek Helio G99 (6nm)"),
      s("💾","RAM","8GB"),
      s("💾","Almacenamiento","256GB (Expandible a 1TB)"),
      s("📷","Cámara principal","50MP + 5MP + 2MP (Macro)"),
      s("📷","Cámara frontal","13MP"),
      s("🔋","Batería","5000mAh / Carga rápida 25W"),
      s("🔥","Sistema operativo","Android 15 + One UI 7.1"),
      s("✅","Lector de Huella","Lateral"),
      s("💦","Resistencia","IP54"),
      s("✨","Diseño","Key Island con acabado brillante"),
      s("🌀","Galaxy AI","Funciones básicas de edición"),
    ],
    "Galaxy A36 5G 8+256GB": [
      s("📱","Pantalla","6.7\" Super AMOLED (120Hz / 1900 nits)"),
      s("⚙️","Procesador","Snapdragon 6 Gen 3 (4nm)"),
      s("💾","RAM","8GB"),
      s("💾","Almacenamiento","256GB"),
      s("📷","Cámara principal","50MP (OIS) + 8MP (Ultra Gran Angular) + 5MP (Macro)"),
      s("📷","Cámara frontal","12MP"),
      s("🔋","Batería","5000mAh / Carga rápida 45W"),
      s("🔥","Sistema operativo","Android 15 (Actualizable hasta Android 21)"),
      s("✅","Lector de Huella","Óptico en pantalla"),
      s("💦","Resistencia","IP67 (Sumergible hasta 1m)"),
      s("✨","Diseño","Perfil delgado (7.4mm) con Gorilla Glass Victus+"),
      s("🌀","Galaxy AI","Funciones de Inteligencia Asombrosa"),
    ],
    "Galaxy A56 5G 12+256GB": [
      s("📱","Pantalla","6.7\" Super AMOLED (120Hz / 1900 nits)"),
      s("⚙️","Procesador","Exynos 1580 (4nm)"),
      s("💾","RAM","12GB"),
      s("💾","Almacenamiento","256GB"),
      s("📷","Cámara principal","50MP (OIS) + 12MP (Ultra Gran Angular) + 5MP (Macro)"),
      s("📷","Cámara frontal","12MP"),
      s("🔋","Batería","5000mAh / Carga rápida 45W"),
      s("🔥","Sistema operativo","Android 15 (Actualizable hasta Android 21)"),
      s("✅","Lector de Huella","Óptico en pantalla"),
      s("💦","Resistencia","IP67 (Sumergible hasta 1m)"),
      s("✨","Diseño","Vidrio Victus+ y marco de aluminio (7.4mm)"),
      s("🌀","Galaxy AI","Inteligencia avanzada y Object Eraser"),
    ],
    "Galaxy A37 5G 8+256GB": [
      s("📱","Pantalla","6.7\" Super AMOLED (120Hz / 1900 nits)"),
      s("⚙️","Procesador","Exynos 1480 (4nm)"),
      s("💾","RAM","8GB"),
      s("💾","Almacenamiento","256GB"),
      s("📷","Cámara principal","50MP (OIS) + 8MP (Ultra Gran Angular) + 5MP (Macro)"),
      s("📷","Cámara frontal","12MP"),
      s("🔋","Batería","5000mAh / Carga rápida 45W"),
      s("🔥","Sistema operativo","Android 16 + One UI 8.5"),
      s("✅","Lector de Huella","Óptico en pantalla"),
      s("💦","Resistencia","IP68 (Sumergible hasta 1.5m)"),
      s("✨","Diseño","Gorilla Glass Victus+ (Frente y Posterior)"),
      s("🌀","Galaxy AI","Circle to Search y Gemini Live"),
    ],
    "Galaxy A57 5G 8+256GB": [
      s("📱","Pantalla","6.7\" Super AMOLED Plus (120Hz / 1900 nits)"),
      s("⚙️","Procesador","Exynos 1680 (4nm)"),
      s("💾","RAM","8GB"),
      s("💾","Almacenamiento","256GB"),
      s("📷","Cámara principal","50MP (OIS) + 12MP + 5MP"),
      s("📷","Cámara frontal","12MP"),
      s("🔋","Batería","5000mAh / Carga rápida 45W"),
      s("🔥","Sistema operativo","Android 16 + One UI 8.5"),
      s("✅","Lector de Huella","Óptico en pantalla"),
      s("💦","Resistencia","IP68 (Sumergible)"),
      s("✨","Diseño","Ultra delgado (6.9mm)"),
      s("🌀","Galaxy AI","Inteligencia Artificial avanzada"),
    ],
    "Galaxy A57 5G 12+512GB": [
      s("📱","Pantalla","6.7\" Super AMOLED Plus (120Hz / 1900 nits)"),
      s("⚙️","Procesador","Exynos 1680 (4nm)"),
      s("💾","RAM","12GB"),
      s("💾","Almacenamiento","512GB"),
      s("📷","Cámara principal","50MP (OIS) + 12MP + 5MP"),
      s("📷","Cámara frontal","12MP"),
      s("🔋","Batería","5000mAh / Carga rápida 45W"),
      s("🔥","Sistema operativo","Android 16 + One UI 8.5"),
      s("✅","Lector de Huella","Óptico en pantalla"),
      s("💦","Resistencia","IP68 (Sumergible)"),
      s("✨","Diseño","Ultra delgado (6.9mm)"),
      s("🌀","Galaxy AI","Inteligencia Artificial avanzada"),
    ],
    "Galaxy S26 12R+256GB": [
      s("📱","Pantalla","6.2\" Dynamic AMOLED 2X (120Hz / 2600 nits)"),
      s("⚙️","Procesador","Snapdragon 8 Gen 5 / Exynos 2600"),
      s("💾","RAM","12GB"),
      s("💾","Almacenamiento","256GB"),
      s("📷","Cámara principal","50MP (Dual Pixel) + 12MP + 10MP (3x Zoom)"),
      s("📷","Cámara frontal","12MP (Dual Pixel)"),
      s("🔋","Batería","4000mAh / Carga rápida 25W"),
      s("🔥","Sistema operativo","Android 16 + One UI 8.5"),
      s("✅","Lector de Huella","Ultrasónico en pantalla"),
      s("💦","Resistencia","IP68 (Sumergible)"),
      s("✨","Diseño","Titanium Frame (Grado 2)"),
      s("🌀","Galaxy AI","Galaxy AI 2.0 (Procesamiento local)"),
    ],
    "Galaxy S26 Ultra 12R+256GB": [
      s("📱","Pantalla","6.9\" Dynamic AMOLED 2X (144Hz / 3000 nits)"),
      s("⚙️","Procesador","Snapdragon 8 Gen 5 for Galaxy"),
      s("💾","RAM","12GB"),
      s("💾","Almacenamiento","256GB"),
      s("📷","Cámara principal","200MP + 50MP (5x) + 10MP (3x) + 12MP"),
      s("📷","Cámara frontal","12MP (Dual Pixel)"),
      s("🔋","Batería","5000mAh / Carga rápida 45W"),
      s("🔥","Sistema operativo","Android 16 + One UI 8.5"),
      s("✅","Lector de Huella","Ultrasónico 3D Max"),
      s("💦","Resistencia","IP68 (Sumergible)"),
      s("✨","Diseño","Titanium Frame (Grado 5) + S-Pen"),
      s("🌀","Galaxy AI","Galaxy AI 2.0 (Video AI generativo)"),
    ],
    "Galaxy S26 Ultra 12R+512GB": [
      s("📱","Pantalla","6.9\" Dynamic AMOLED 2X (144Hz / 3000 nits)"),
      s("⚙️","Procesador","Snapdragon 8 Gen 5 for Galaxy"),
      s("💾","RAM","12GB"),
      s("💾","Almacenamiento","512GB"),
      s("📷","Cámara principal","200MP + 50MP (5x) + 10MP (3x) + 12MP"),
      s("📷","Cámara frontal","12MP (Dual Pixel)"),
      s("🔋","Batería","5000mAh / Carga rápida 45W"),
      s("🔥","Sistema operativo","Android 16 + One UI 8.5"),
      s("✅","Lector de Huella","Ultrasónico 3D Max"),
      s("💦","Resistencia","IP68 (Sumergible)"),
      s("✨","Diseño","Titanium Frame (Grado 5) + S-Pen"),
      s("🌀","Galaxy AI","Galaxy AI 2.0 (Video AI generativo)"),
    ],
    "Galaxy S26 Ultra 16R+1TB": [
      s("📱","Pantalla","6.9\" Dynamic AMOLED 2X (144Hz / 3000 nits)"),
      s("⚙️","Procesador","Snapdragon 8 Gen 5 for Galaxy"),
      s("💾","RAM","16GB"),
      s("💾","Almacenamiento","1TB (UFS 4.1)"),
      s("📷","Cámara principal","200MP + 50MP (5x) + 10MP (3x) + 12MP"),
      s("📷","Cámara frontal","12MP (Dual Pixel)"),
      s("🔋","Batería","5000mAh / Carga rápida 45W"),
      s("🔥","Sistema operativo","Android 16 + One UI 8.5"),
      s("✅","Lector de Huella","Ultrasónico 3D Max"),
      s("💦","Resistencia","IP68 (Sumergible)"),
      s("✨","Diseño","Titanium Frame (Grado 5) + S-Pen"),
      s("🌀","Galaxy AI","Galaxy AI 2.0 (Multimodal avanzado)"),
    ],
    "Infinix Smart 10 4+128GB": [
      s("📱","Pantalla","6.6\" IPS LCD (90Hz / 500 nits)"),
      s("⚙️","Procesador","Unisoc T606 (12nm)"),
      s("💾","RAM","4GB"),
      s("💾","Almacenamiento","128GB (Expandible)"),
      s("📷","Cámara principal","13MP + AI Lens"),
      s("📷","Cámara frontal","8MP"),
      s("🔋","Batería","5000mAh / Carga de 10W"),
      s("🔥","Sistema operativo","Android 14 (Go Edition)"),
      s("✅","Lector de Huella","Lateral"),
      s("💦","Resistencia","No certificada"),
      s("✨","Diseño","Textura antibacteriana"),
    ],
    "Infinix Smart 20 4+128GB": [
      s("📱","Pantalla","6.7\" IPS LCD (90Hz / Magic Ring)"),
      s("⚙️","Procesador","MediaTek Helio G36 (12nm)"),
      s("💾","RAM","4GB"),
      s("💾","Almacenamiento","128GB"),
      s("📷","Cámara principal","50MP + AI"),
      s("📷","Cámara frontal","8MP (Dual Flash)"),
      s("🔋","Batería","5000mAh / Carga rápida 18W"),
      s("🔥","Sistema operativo","Android 15"),
      s("✅","Lector de Huella","Lateral"),
      s("💦","Resistencia","IP53 (Salpicaduras)"),
      s("✨","Diseño","Acabado tipo cristal"),
      s("🌀","Folax AI","Asistente de voz básico"),
    ],
    "Infinix Hot 60I 4+256GB": [
      s("📱","Pantalla","6.7\" IPS LCD (120Hz / 500 nits)"),
      s("⚙️","Procesador","MediaTek Helio G81"),
      s("💾","RAM","4GB"),
      s("💾","Almacenamiento","256GB"),
      s("📷","Cámara principal","48MP + AI Lens"),
      s("📷","Cámara frontal","8MP"),
      s("🔋","Batería","5000mAh / Carga rápida 18W"),
      s("🔥","Sistema operativo","Android 14"),
      s("✅","Lector de Huella","Lateral"),
      s("💦","Resistencia","IP54"),
      s("✨","Diseño","Slim Body (8.1mm)"),
    ],
    "Infinix Hot 60I 8+256GB": [
      s("📱","Pantalla","6.7\" IPS LCD (120Hz / 500 nits)"),
      s("⚙️","Procesador","MediaTek Helio G81"),
      s("💾","RAM","8GB"),
      s("💾","Almacenamiento","256GB"),
      s("📷","Cámara principal","48MP + AI Lens"),
      s("📷","Cámara frontal","8MP"),
      s("🔋","Batería","5000mAh / Carga rápida 18W"),
      s("🔥","Sistema operativo","Android 14"),
      s("✅","Lector de Huella","Lateral"),
      s("💦","Resistencia","IP54"),
      s("✨","Diseño","Slim Body (8.1mm)"),
    ],
    "Infinix Hot 60 Pro Plus 8+256GB": [
      s("📱","Pantalla","6.78\" AMOLED (120Hz / Curva 3D)"),
      s("⚙️","Procesador","MediaTek Helio G100 (6nm)"),
      s("💾","RAM","8GB"),
      s("💾","Almacenamiento","256GB"),
      s("📷","Cámara principal","108MP (OIS) + 2MP + AI"),
      s("📷","Cámara frontal","32MP"),
      s("🔋","Batería","5000mAh / Carga rápida 45W"),
      s("🔥","Sistema operativo","Android 15"),
      s("✅","Lector de Huella","En pantalla (Óptico)"),
      s("💦","Resistencia","IP54"),
      s("✨","Diseño","Ultra delgado (6.8mm)"),
      s("🌀","Folax AI","IA generativa de texto y voz"),
    ],
    "Infinix Note 60 5G 8+256GB": [
      s("📱","Pantalla","6.8\" IPS LCD (120Hz / Variable Refresh)"),
      s("⚙️","Procesador","MediaTek Dimensity 6300 5G"),
      s("💾","RAM","8GB"),
      s("💾","Almacenamiento","256GB"),
      s("📷","Cámara principal","108MP + 2MP"),
      s("📷","Cámara frontal","16MP"),
      s("🔋","Batería","5000mAh / Carga rápida 33W"),
      s("🔥","Sistema operativo","Android 15"),
      s("✅","Lector de Huella","Lateral"),
      s("💦","Resistencia","IP53"),
      s("✨","Diseño","Titanium Look Texture"),
      s("🌀","Folax AI","Reducción de ruido por IA"),
    ],
    "Infinix Note 60 Pro 8+256GB": [
      s("📱","Pantalla","6.78\" AMOLED (144Hz / 1300 nits)"),
      s("⚙️","Procesador","MediaTek Dimensity 8050"),
      s("💾","RAM","8GB"),
      s("💾","Almacenamiento","256GB"),
      s("📷","Cámara principal","108MP (OIS) + 13MP (UW) + 2MP"),
      s("📷","Cámara frontal","32MP"),
      s("🔋","Batería","5000mAh / Carga rápida 68W + Inalámbrica"),
      s("🔥","Sistema operativo","Android 15"),
      s("✅","Lector de Huella","En pantalla"),
      s("💦","Resistencia","IP54"),
      s("✨","Diseño","Active Halo Lighting (LED posterior)"),
      s("🌀","Folax AI","Integración avanzada de IA"),
    ],
    "Tecno Spark GO3 4R+128GB": [
      s("📱","Pantalla","6.6\" IPS LCD (90Hz / Magic Ring)"),
      s("⚙️","Procesador","Unisoc T606 (12nm)"),
      s("💾","RAM","4GB"),
      s("💾","Almacenamiento","128GB (Expandible)"),
      s("📷","Cámara principal","13MP + AI Lens"),
      s("📷","Cámara frontal","8MP"),
      s("🔋","Batería","5000mAh / Carga de 10W"),
      s("🔥","Sistema operativo","Android 14 (Go Edition)"),
      s("✅","Lector de Huella","Lateral"),
      s("💦","Resistencia","IP54 (Polvo y salpicaduras)"),
      s("✨","Diseño","Acabado Sparkle Texture"),
    ],
    "Tecno Spark 40C 8+256GB": [
      s("📱","Pantalla","6.67\" IPS LCD (120Hz / HD+)"),
      s("⚙️","Procesador","MediaTek Helio G81"),
      s("💾","RAM","8GB"),
      s("💾","Almacenamiento","256GB"),
      s("📷","Cámara principal","50MP + AI Lens"),
      s("📷","Cámara frontal","8MP (Dual Flash)"),
      s("🔋","Batería","5000mAh / Carga rápida 18W"),
      s("🔥","Sistema operativo","Android 14 + HiOS 14"),
      s("✅","Lector de Huella","Lateral"),
      s("💦","Resistencia","IP54"),
      s("✨","Diseño","Dynamic Port 2.0"),
    ],
    "Tecno Spark 50 4+256GB": [
      s("📱","Pantalla","6.7\" IPS LCD (120Hz / Full HD+)"),
      s("⚙️","Procesador","MediaTek Helio G91"),
      s("💾","RAM","4GB"),
      s("💾","Almacenamiento","256GB"),
      s("📷","Cámara principal","50MP + 2MP (Profundidad)"),
      s("📷","Cámara frontal","13MP"),
      s("🔋","Batería","5000mAh / Carga rápida 18W"),
      s("🔥","Sistema operativo","Android 15 + HiOS 15"),
      s("✅","Lector de Huella","Lateral"),
      s("💦","Resistencia","IP54"),
      s("✨","Diseño","Cuerpo ultra delgado"),
      s("🌀","Ella AI","Asistente personal con IA"),
    ],
    "Tecno Camon 50 Pro 8+256GB": [
      s("📱","Pantalla","6.78\" AMOLED (144Hz / LTPO)"),
      s("⚙️","Procesador","MediaTek Dimensity 8300 Ultra"),
      s("💾","RAM","8GB"),
      s("💾","Almacenamiento","256GB"),
      s("📷","Cámara principal","50MP (OIS) + 50MP (Telefoto) + 50MP (UW)"),
      s("📷","Cámara frontal","50MP (Autofocus)"),
      s("🔋","Batería","5000mAh / Carga rápida 70W"),
      s("🔥","Sistema operativo","Android 15 + HiOS 15"),
      s("✅","Lector de Huella","En pantalla"),
      s("💦","Resistencia","IP68 (Sumergible)"),
      s("✨","Diseño","Nature Flow (Acabado de cuero vegano)"),
      s("🌀","Ella AI","IA Generativa y traducción en tiempo real"),
    ],
    "Tecno Camon 50 Ultra 8R+256GB": [
      s("📱","Pantalla","6.8\" AMOLED Curva (144Hz / 2500 nits)"),
      s("⚙️","Procesador","MediaTek Dimensity 9400"),
      s("💾","RAM","8GB (Física)"),
      s("💾","Almacenamiento","256GB (UFS 4.0)"),
      s("📷","Cámara principal","50MP (Sensor 1) + 50MP (Periscopio 5x) + 50MP"),
      s("📷","Cámara frontal","50MP (Eye Tracking AF)"),
      s("🔋","Batería","5500mAh / Carga rápida 100W + Inalámbrica"),
      s("🔥","Sistema operativo","Android 15 + HiOS 15"),
      s("✅","Lector de Huella","Ultrasónico en pantalla"),
      s("💦","Resistencia","IP68 (Sumergible)"),
      s("✨","Diseño","Borde infinito con marco de aleación"),
      s("🌀","Ella AI","IA Multimodal avanzada"),
    ],
  };

  // ── Cargar a Firebase ────────────────────────────────────────────────
  console.log("🔍 Leyendo productos de Firebase...");
  const prodSnap  = await getDocs(collection(db, "productos"));
  const productos = prodSnap.docs.map(d => ({ id: d.id, nombre: d.data().nombre }));
  console.log(`📦 ${productos.length} productos encontrados`);
  console.log("🚀 Cargando especificaciones...");

  let cargados = 0;
  let noEncontrados = [];

  for (const [nombre, items] of Object.entries(SPECS_DB)) {
    const prod = productos.find(p => p.nombre === nombre);
    if (!prod) { noEncontrados.push(nombre); continue; }
    await setDoc(doc(db, "specs", prod.id), { items, updatedAt: serverTimestamp() });
    console.log(`  ✅ ${nombre}`);
    cargados++;
  }

  console.log(`\n🎉 ¡Listo! ${cargados} productos con specs cargados.`);
  if (noEncontrados.length > 0) {
    console.warn("⚠️ No encontrados en la base de datos:");
    noEncontrados.forEach(n => console.warn(`   - ${n}`));
  }
  console.log("↩️ Recarga la página del catálogo para ver los cambios.");
})();
