// ── Specs Database ────────────────────────────────────────────────────────
// Cada entrada: nombre exacto del producto → array de [emoji, label, valor]
export const SPECS_DB = {
  // ── APPLE ──────────────────────────────────────────────────────────────
  "iPhone 15 Pro Max 256GB eSIM": [
    ["📱","Pantalla","6.7\" LTPO Super Retina XDR OLED (120Hz / 2000 nits)"],
    ["⚙️","Procesador","A17 Pro (3nm)"],
    ["💾","RAM","8GB"],
    ["💾","Almacenamiento","256GB"],
    ["📷","Cámara principal","48MP (OIS) + 12MP (Telefoto 5x) + 12MP (Ultra Gran Angular)"],
    ["📷","Cámara frontal","12MP (TrueDepth)"],
    ["🔋","Batería","4441mAh / Carga rápida 20W"],
    ["🔥","Sistema operativo","iOS 17 (Actualizable a iOS 19+)"],
    ["✅","Lector de Huella","No (Face ID)"],
    ["💦","Resistencia","IP68 (Sumergible hasta 6m por 30 min)"],
    ["✨","Diseño","Titanio de grado aeroespacial / Botón de Acción"],
    ["🌀","Apple Intelligence","Compatible (Beta)"],
  ],
  "iPhone 16 Pro Max 512GB eSIM": [
    ["📱","Pantalla","6.9\" LTPO Super Retina XDR OLED (120Hz / 2000 nits)"],
    ["⚙️","Procesador","A18 Pro (3nm)"],
    ["💾","RAM","8GB"],
    ["💾","Almacenamiento","512GB"],
    ["📷","Cámara principal","48MP (Fusion) + 48MP (Ultra Gran Angular) + 12MP (Telefoto 5x)"],
    ["📷","Cámara frontal","12MP (TrueDepth)"],
    ["🔋","Batería","4685mAh / Carga rápida 30W"],
    ["🔥","Sistema operativo","iOS 18"],
    ["✅","Lector de Huella","No (Face ID)"],
    ["💦","Resistencia","IP68 (Sumergible hasta 6m por 30 min)"],
    ["✨","Diseño","Chasis de Titanio / Control de Cámara (Botón táctil)"],
    ["🌀","Apple Intelligence","Integración nativa avanzada"],
  ],
  "iPhone 17 Pro Max 256GB eSIM": [
    ["📱","Pantalla","6.9\" LTPO Super Retina XDR (120Hz / 2500 nits)"],
    ["⚙️","Procesador","A19 Pro (2nm)"],
    ["💾","RAM","12GB"],
    ["💾","Almacenamiento","256GB"],
    ["📷","Cámara principal","48MP + 48MP (Ultra Gran Angular) + 48MP (Telefoto 5x)"],
    ["📷","Cámara frontal","24MP (TrueDepth)"],
    ["🔋","Batería","4800mAh / Carga rápida 45W"],
    ["🔥","Sistema operativo","iOS 19"],
    ["✅","Lector de Huella","No (Face ID bajo pantalla)"],
    ["💦","Resistencia","IP68 (Sumergible)"],
    ["✨","Diseño","Titanio reforzado / Isla Dinámica reducida"],
    ["🌀","Apple Intelligence","IA Generativa local mejorada"],
  ],
  "iPhone 17 Pro Max 512GB eSIM": [
    ["📱","Pantalla","6.9\" LTPO Super Retina XDR (120Hz / 2500 nits)"],
    ["⚙️","Procesador","A19 Pro (2nm)"],
    ["💾","RAM","12GB"],
    ["💾","Almacenamiento","512GB"],
    ["📷","Cámara principal","48MP + 48MP (Ultra Gran Angular) + 48MP (Telefoto 5x)"],
    ["📷","Cámara frontal","24MP (TrueDepth)"],
    ["🔋","Batería","4800mAh / Carga rápida 45W"],
    ["🔥","Sistema operativo","iOS 19"],
    ["✅","Lector de Huella","No (Face ID bajo pantalla)"],
    ["💦","Resistencia","IP68 (Sumergible)"],
    ["✨","Diseño","Titanio reforzado / Isla Dinámica reducida"],
    ["🌀","Apple Intelligence","IA Generativa local mejorada"],
  ],
  // ── SAMSUNG ────────────────────────────────────────────────────────────
  "Galaxy A07 4+128GB": [
    ["📱","Pantalla","6.7\" PLS LCD (60Hz / HD+)"],
    ["⚙️","Procesador","MediaTek Helio G85 (12nm)"],
    ["💾","RAM","4GB"],
    ["💾","Almacenamiento","128GB (Expandible a 1TB)"],
    ["📷","Cámara principal","50MP + 2MP (Sensor de profundidad)"],
    ["📷","Cámara frontal","8MP"],
    ["🔋","Batería","5000mAh / Carga rápida 25W"],
    ["🔥","Sistema operativo","Android 13 (Actualizable a Android 14)"],
    ["✅","Lector de Huella","No posee (Reconocimiento facial)"],
    ["💦","Resistencia","Sin certificación IP"],
    ["✨","Diseño","Acabado con textura lineal"],
    ["🌀","Galaxy AI","No disponible"],
  ],
  "Galaxy A16 4+128GB": [
    ["📱","Pantalla","6.7\" Super AMOLED (90Hz / Full HD+)"],
    ["⚙️","Procesador","Exynos 1330 / Dimensity 6300"],
    ["💾","RAM","4GB"],
    ["💾","Almacenamiento","128GB (Expandible a 1TB)"],
    ["📷","Cámara principal","50MP + 5MP (Ultra Gran Angular) + 2MP (Macro)"],
    ["📷","Cámara frontal","13MP"],
    ["🔋","Batería","5000mAh / Carga rápida 25W"],
    ["🔥","Sistema operativo","Android 14 (6 años de actualizaciones)"],
    ["✅","Lector de Huella","Lateral (En el botón de encendido)"],
    ["💦","Resistencia","IP54 (Polvo y salpicaduras)"],
    ["✨","Diseño","Key Island con acabado brillante"],
    ["🌀","Galaxy AI","No disponible"],
  ],
  "Galaxy A17 4G 4+128GB": [
    ["📱","Pantalla","6.7\" Super AMOLED (90Hz / Full HD+)"],
    ["⚙️","Procesador","MediaTek Helio G99 (6nm)"],
    ["💾","RAM","4GB"],
    ["💾","Almacenamiento","128GB (Expandible a 1TB)"],
    ["📷","Cámara principal","50MP + 5MP (Ultra Gran Angular) + 2MP (Macro)"],
    ["📷","Cámara frontal","13MP"],
    ["🔋","Batería","5000mAh / Carga rápida 25W"],
    ["🔥","Sistema operativo","Android 15 + One UI 7.1"],
    ["✅","Lector de Huella","Lateral"],
    ["💦","Resistencia","IP54"],
    ["✨","Diseño","Key Island con acabado brillante"],
    ["🌀","Galaxy AI","Funciones básicas de edición"],
  ],
  "Galaxy A17 4G 6+128GB": [
    ["📱","Pantalla","6.7\" Super AMOLED (90Hz / Full HD+)"],
    ["⚙️","Procesador","MediaTek Helio G99 (6nm)"],
    ["💾","RAM","6GB"],
    ["💾","Almacenamiento","128GB (Expandible a 1TB)"],
    ["📷","Cámara principal","50MP + 5MP + 2MP (Macro)"],
    ["📷","Cámara frontal","13MP"],
    ["🔋","Batería","5000mAh / Carga rápida 25W"],
    ["🔥","Sistema operativo","Android 15 + One UI 7.1"],
    ["✅","Lector de Huella","Lateral"],
    ["💦","Resistencia","IP54"],
    ["✨","Diseño","Key Island con acabado brillante"],
    ["🌀","Galaxy AI","Funciones básicas de edición"],
  ],
  "Galaxy A17 4G 8+256GB": [
    ["📱","Pantalla","6.7\" Super AMOLED (90Hz / Full HD+)"],
    ["⚙️","Procesador","MediaTek Helio G99 (6nm)"],
    ["💾","RAM","8GB"],
    ["💾","Almacenamiento","256GB (Expandible a 1TB)"],
    ["📷","Cámara principal","50MP + 5MP + 2MP (Macro)"],
    ["📷","Cámara frontal","13MP"],
    ["🔋","Batería","5000mAh / Carga rápida 25W"],
    ["🔥","Sistema operativo","Android 15 + One UI 7.1"],
    ["✅","Lector de Huella","Lateral"],
    ["💦","Resistencia","IP54"],
    ["✨","Diseño","Key Island con acabado brillante"],
    ["🌀","Galaxy AI","Funciones básicas de edición"],
  ],
  "Galaxy A36 5G 8+256GB": [
    ["📱","Pantalla","6.7\" Super AMOLED (120Hz / 1900 nits)"],
    ["⚙️","Procesador","Snapdragon 6 Gen 3 (4nm)"],
    ["💾","RAM","8GB"],
    ["💾","Almacenamiento","256GB"],
    ["📷","Cámara principal","50MP (OIS) + 8MP (Ultra Gran Angular) + 5MP (Macro)"],
    ["📷","Cámara frontal","12MP"],
    ["🔋","Batería","5000mAh / Carga rápida 45W"],
    ["🔥","Sistema operativo","Android 15 (Actualizable hasta Android 21)"],
    ["✅","Lector de Huella","Óptico en pantalla"],
    ["💦","Resistencia","IP67 (Sumergible hasta 1m)"],
    ["✨","Diseño","Perfil delgado (7.4mm) con Gorilla Glass Victus+"],
    ["🌀","Galaxy AI","Funciones de Inteligencia Asombrosa"],
  ],
  "Galaxy A56 5G 12+256GB": [
    ["📱","Pantalla","6.7\" Super AMOLED (120Hz / 1900 nits)"],
    ["⚙️","Procesador","Exynos 1580 (4nm)"],
    ["💾","RAM","12GB"],
    ["💾","Almacenamiento","256GB"],
    ["📷","Cámara principal","50MP (OIS) + 12MP (Ultra Gran Angular) + 5MP (Macro)"],
    ["📷","Cámara frontal","12MP"],
    ["🔋","Batería","5000mAh / Carga rápida 45W"],
    ["🔥","Sistema operativo","Android 15 (Actualizable hasta Android 21)"],
    ["✅","Lector de Huella","Óptico en pantalla"],
    ["💦","Resistencia","IP67 (Sumergible hasta 1m)"],
    ["✨","Diseño","Vidrio Victus+ y marco de aluminio (7.4mm)"],
    ["🌀","Galaxy AI","Inteligencia avanzada y Object Eraser"],
  ],
  "Galaxy A37 5G 8+256GB": [
    ["📱","Pantalla","6.7\" Super AMOLED (120Hz / 1900 nits)"],
    ["⚙️","Procesador","Exynos 1480 (4nm)"],
    ["💾","RAM","8GB"],
    ["💾","Almacenamiento","256GB"],
    ["📷","Cámara principal","50MP (OIS) + 8MP (Ultra Gran Angular) + 5MP (Macro)"],
    ["📷","Cámara frontal","12MP"],
    ["🔋","Batería","5000mAh / Carga rápida 45W"],
    ["🔥","Sistema operativo","Android 16 + One UI 8.5"],
    ["✅","Lector de Huella","Óptico en pantalla"],
    ["💦","Resistencia","IP68 (Sumergible hasta 1.5m)"],
    ["✨","Diseño","Gorilla Glass Victus+ (Frente y Posterior)"],
    ["🌀","Galaxy AI","Circle to Search y Gemini Live"],
  ],
  "Galaxy A57 5G 8+256GB": [
    ["📱","Pantalla","6.7\" Super AMOLED Plus (120Hz / 1900 nits)"],
    ["⚙️","Procesador","Exynos 1680 (4nm)"],
    ["💾","RAM","8GB"],
    ["💾","Almacenamiento","256GB"],
    ["📷","Cámara principal","50MP (OIS) + 12MP + 5MP"],
    ["📷","Cámara frontal","12MP"],
    ["🔋","Batería","5000mAh / Carga rápida 45W"],
    ["🔥","Sistema operativo","Android 16 + One UI 8.5"],
    ["✅","Lector de Huella","Óptico en pantalla"],
    ["💦","Resistencia","IP68 (Sumergible)"],
    ["✨","Diseño","Ultra delgado (6.9mm)"],
    ["🌀","Galaxy AI","Inteligencia Artificial avanzada"],
  ],
  "Galaxy A57 5G 12+512GB": [
    ["📱","Pantalla","6.7\" Super AMOLED Plus (120Hz / 1900 nits)"],
    ["⚙️","Procesador","Exynos 1680 (4nm)"],
    ["💾","RAM","12GB"],
    ["💾","Almacenamiento","512GB"],
    ["📷","Cámara principal","50MP (OIS) + 12MP + 5MP"],
    ["📷","Cámara frontal","12MP"],
    ["🔋","Batería","5000mAh / Carga rápida 45W"],
    ["🔥","Sistema operativo","Android 16 + One UI 8.5"],
    ["✅","Lector de Huella","Óptico en pantalla"],
    ["💦","Resistencia","IP68 (Sumergible)"],
    ["✨","Diseño","Ultra delgado (6.9mm)"],
    ["🌀","Galaxy AI","Inteligencia Artificial avanzada"],
  ],
  "Galaxy S26 12R+256GB": [
    ["📱","Pantalla","6.2\" Dynamic AMOLED 2X (120Hz / 2600 nits)"],
    ["⚙️","Procesador","Snapdragon 8 Gen 5 / Exynos 2600"],
    ["💾","RAM","12GB"],
    ["💾","Almacenamiento","256GB"],
    ["📷","Cámara principal","50MP (Dual Pixel) + 12MP + 10MP (3x Zoom)"],
    ["📷","Cámara frontal","12MP (Dual Pixel)"],
    ["🔋","Batería","4000mAh / Carga rápida 25W"],
    ["🔥","Sistema operativo","Android 16 + One UI 8.5"],
    ["✅","Lector de Huella","Ultrasónico en pantalla"],
    ["💦","Resistencia","IP68 (Sumergible)"],
    ["✨","Diseño","Titanium Frame (Grado 2)"],
    ["🌀","Galaxy AI","Galaxy AI 2.0 (Procesamiento local)"],
  ],
  "Galaxy S26 Ultra 12R+256GB": [
    ["📱","Pantalla","6.9\" Dynamic AMOLED 2X (144Hz / 3000 nits)"],
    ["⚙️","Procesador","Snapdragon 8 Gen 5 for Galaxy"],
    ["💾","RAM","12GB"],
    ["💾","Almacenamiento","256GB"],
    ["📷","Cámara principal","200MP + 50MP (5x) + 10MP (3x) + 12MP"],
    ["📷","Cámara frontal","12MP (Dual Pixel)"],
    ["🔋","Batería","5000mAh / Carga rápida 45W"],
    ["🔥","Sistema operativo","Android 16 + One UI 8.5"],
    ["✅","Lector de Huella","Ultrasónico 3D Max"],
    ["💦","Resistencia","IP68 (Sumergible)"],
    ["✨","Diseño","Titanium Frame (Grado 5) + S-Pen"],
    ["🌀","Galaxy AI","Galaxy AI 2.0 (Video AI generativo)"],
  ],
  "Galaxy S26 Ultra 12R+512GB": [
    ["📱","Pantalla","6.9\" Dynamic AMOLED 2X (144Hz / 3000 nits)"],
    ["⚙️","Procesador","Snapdragon 8 Gen 5 for Galaxy"],
    ["💾","RAM","12GB"],
    ["💾","Almacenamiento","512GB"],
    ["📷","Cámara principal","200MP + 50MP (5x) + 10MP (3x) + 12MP"],
    ["📷","Cámara frontal","12MP (Dual Pixel)"],
    ["🔋","Batería","5000mAh / Carga rápida 45W"],
    ["🔥","Sistema operativo","Android 16 + One UI 8.5"],
    ["✅","Lector de Huella","Ultrasónico 3D Max"],
    ["💦","Resistencia","IP68 (Sumergible)"],
    ["✨","Diseño","Titanium Frame (Grado 5) + S-Pen"],
    ["🌀","Galaxy AI","Galaxy AI 2.0 (Video AI generativo)"],
  ],
  "Galaxy S26 Ultra 16R+1TB": [
    ["📱","Pantalla","6.9\" Dynamic AMOLED 2X (144Hz / 3000 nits)"],
    ["⚙️","Procesador","Snapdragon 8 Gen 5 for Galaxy"],
    ["💾","RAM","16GB"],
    ["💾","Almacenamiento","1TB (UFS 4.1)"],
    ["📷","Cámara principal","200MP + 50MP (5x) + 10MP (3x) + 12MP"],
    ["📷","Cámara frontal","12MP (Dual Pixel)"],
    ["🔋","Batería","5000mAh / Carga rápida 45W"],
    ["🔥","Sistema operativo","Android 16 + One UI 8.5"],
    ["✅","Lector de Huella","Ultrasónico 3D Max"],
    ["💦","Resistencia","IP68 (Sumergible)"],
    ["✨","Diseño","Titanium Frame (Grado 5) + S-Pen"],
    ["🌀","Galaxy AI","Galaxy AI 2.0 (Multimodal avanzado)"],
  ],
  // ── INFINIX ────────────────────────────────────────────────────────────
  "Infinix Smart 10 4+128GB": [
    ["📱","Pantalla","6.6\" IPS LCD (90Hz / 500 nits)"],
    ["⚙️","Procesador","Unisoc T606 (12nm)"],
    ["💾","RAM","4GB"],
    ["💾","Almacenamiento","128GB (Expandible)"],
    ["📷","Cámara principal","13MP + AI Lens"],
    ["📷","Cámara frontal","8MP"],
    ["🔋","Batería","5000mAh / Carga de 10W"],
    ["🔥","Sistema operativo","Android 14 (Go Edition)"],
    ["✅","Lector de Huella","Lateral"],
    ["💦","Resistencia","No certificada"],
    ["✨","Diseño","Textura antibacteriana"],
  ],
  "Infinix Smart 20 4+128GB": [
    ["📱","Pantalla","6.7\" IPS LCD (90Hz / Magic Ring)"],
    ["⚙️","Procesador","MediaTek Helio G36 (12nm)"],
    ["💾","RAM","4GB"],
    ["💾","Almacenamiento","128GB"],
    ["📷","Cámara principal","50MP + AI"],
    ["📷","Cámara frontal","8MP (Dual Flash)"],
    ["🔋","Batería","5000mAh / Carga rápida 18W"],
    ["🔥","Sistema operativo","Android 15"],
    ["✅","Lector de Huella","Lateral"],
    ["💦","Resistencia","IP53 (Salpicaduras)"],
    ["✨","Diseño","Acabado tipo cristal"],
    ["🌀","Folax AI","Asistente de voz básico"],
  ],
  "Infinix Hot 60I 4+256GB": [
    ["📱","Pantalla","6.7\" IPS LCD (120Hz / 500 nits)"],
    ["⚙️","Procesador","MediaTek Helio G81"],
    ["💾","RAM","4GB"],
    ["💾","Almacenamiento","256GB"],
    ["📷","Cámara principal","48MP + AI Lens"],
    ["📷","Cámara frontal","8MP"],
    ["🔋","Batería","5000mAh / Carga rápida 18W"],
    ["🔥","Sistema operativo","Android 14"],
    ["✅","Lector de Huella","Lateral"],
    ["💦","Resistencia","IP54"],
    ["✨","Diseño","Slim Body (8.1mm)"],
  ],
  "Infinix Hot 60I 8+256GB": [
    ["📱","Pantalla","6.7\" IPS LCD (120Hz / 500 nits)"],
    ["⚙️","Procesador","MediaTek Helio G81"],
    ["💾","RAM","8GB"],
    ["💾","Almacenamiento","256GB"],
    ["📷","Cámara principal","48MP + AI Lens"],
    ["📷","Cámara frontal","8MP"],
    ["🔋","Batería","5000mAh / Carga rápida 18W"],
    ["🔥","Sistema operativo","Android 14"],
    ["✅","Lector de Huella","Lateral"],
    ["💦","Resistencia","IP54"],
    ["✨","Diseño","Slim Body (8.1mm)"],
  ],
  "Infinix Hot 60 Pro Plus 8+256GB": [
    ["📱","Pantalla","6.78\" AMOLED (120Hz / Curva 3D)"],
    ["⚙️","Procesador","MediaTek Helio G100 (6nm)"],
    ["💾","RAM","8GB"],
    ["💾","Almacenamiento","256GB"],
    ["📷","Cámara principal","108MP (OIS) + 2MP + AI"],
    ["📷","Cámara frontal","32MP"],
    ["🔋","Batería","5000mAh / Carga rápida 45W"],
    ["🔥","Sistema operativo","Android 15"],
    ["✅","Lector de Huella","En pantalla (Óptico)"],
    ["💦","Resistencia","IP54"],
    ["✨","Diseño","Ultra delgado (6.8mm)"],
    ["🌀","Folax AI","IA generativa de texto y voz"],
  ],
  "Infinix Note 60 5G 8+256GB": [
    ["📱","Pantalla","6.8\" IPS LCD (120Hz / Variable Refresh)"],
    ["⚙️","Procesador","MediaTek Dimensity 6300 5G"],
    ["💾","RAM","8GB"],
    ["💾","Almacenamiento","256GB"],
    ["📷","Cámara principal","108MP + 2MP"],
    ["📷","Cámara frontal","16MP"],
    ["🔋","Batería","5000mAh / Carga rápida 33W"],
    ["🔥","Sistema operativo","Android 15"],
    ["✅","Lector de Huella","Lateral"],
    ["💦","Resistencia","IP53"],
    ["✨","Diseño","Titanium Look Texture"],
    ["🌀","Folax AI","Reducción de ruido por IA"],
  ],
  "Infinix Note 60 Pro 8+256GB": [
    ["📱","Pantalla","6.78\" AMOLED (144Hz / 1300 nits)"],
    ["⚙️","Procesador","MediaTek Dimensity 8050"],
    ["💾","RAM","8GB"],
    ["💾","Almacenamiento","256GB"],
    ["📷","Cámara principal","108MP (OIS) + 13MP (UW) + 2MP"],
    ["📷","Cámara frontal","32MP"],
    ["🔋","Batería","5000mAh / Carga rápida 68W + Inalámbrica"],
    ["🔥","Sistema operativo","Android 15"],
    ["✅","Lector de Huella","En pantalla"],
    ["💦","Resistencia","IP54"],
    ["✨","Diseño","Active Halo Lighting (LED posterior)"],
    ["🌀","Folax AI","Integración avanzada de IA"],
  ],
  // ── TECNO ─────────────────────────────────────────────────────────────
  "Tecno Spark GO3 4R+128GB": [
    ["📱","Pantalla","6.6\" IPS LCD (90Hz / Magic Ring)"],
    ["⚙️","Procesador","Unisoc T606 (12nm)"],
    ["💾","RAM","4GB"],
    ["💾","Almacenamiento","128GB (Expandible)"],
    ["📷","Cámara principal","13MP + AI Lens"],
    ["📷","Cámara frontal","8MP"],
    ["🔋","Batería","5000mAh / Carga de 10W"],
    ["🔥","Sistema operativo","Android 14 (Go Edition)"],
    ["✅","Lector de Huella","Lateral"],
    ["💦","Resistencia","IP54 (Polvo y salpicaduras)"],
    ["✨","Diseño","Acabado Sparkle Texture"],
  ],
  "Tecno Spark 40C 8+256GB": [
    ["📱","Pantalla","6.67\" IPS LCD (120Hz / HD+)"],
    ["⚙️","Procesador","MediaTek Helio G81"],
    ["💾","RAM","8GB"],
    ["💾","Almacenamiento","256GB"],
    ["📷","Cámara principal","50MP + AI Lens"],
    ["📷","Cámara frontal","8MP (Dual Flash)"],
    ["🔋","Batería","5000mAh / Carga rápida 18W"],
    ["🔥","Sistema operativo","Android 14 + HiOS 14"],
    ["✅","Lector de Huella","Lateral"],
    ["💦","Resistencia","IP54"],
    ["✨","Diseño","Dynamic Port 2.0"],
  ],
  "Tecno Spark 50 4+256GB": [
    ["📱","Pantalla","6.7\" IPS LCD (120Hz / Full HD+)"],
    ["⚙️","Procesador","MediaTek Helio G91"],
    ["💾","RAM","4GB"],
    ["💾","Almacenamiento","256GB"],
    ["📷","Cámara principal","50MP + 2MP (Profundidad)"],
    ["📷","Cámara frontal","13MP"],
    ["🔋","Batería","5000mAh / Carga rápida 18W"],
    ["🔥","Sistema operativo","Android 15 + HiOS 15"],
    ["✅","Lector de Huella","Lateral"],
    ["💦","Resistencia","IP54"],
    ["✨","Diseño","Cuerpo ultra delgado"],
    ["🌀","Ella AI","Asistente personal con IA"],
  ],
  "Tecno Camon 50 Pro 8+256GB": [
    ["📱","Pantalla","6.78\" AMOLED (144Hz / LTPO)"],
    ["⚙️","Procesador","MediaTek Dimensity 8300 Ultra"],
    ["💾","RAM","8GB"],
    ["💾","Almacenamiento","256GB"],
    ["📷","Cámara principal","50MP (OIS) + 50MP (Telefoto) + 50MP (UW)"],
    ["📷","Cámara frontal","50MP (Autofocus)"],
    ["🔋","Batería","5000mAh / Carga rápida 70W"],
    ["🔥","Sistema operativo","Android 15 + HiOS 15"],
    ["✅","Lector de Huella","En pantalla"],
    ["💦","Resistencia","IP68 (Sumergible)"],
    ["✨","Diseño","Nature Flow (Acabado de cuero vegano)"],
    ["🌀","Ella AI","IA Generativa y traducción en tiempo real"],
  ],
  "Tecno Camon 50 Ultra 8R+256GB": [
    ["📱","Pantalla","6.8\" AMOLED Curva (144Hz / 2500 nits)"],
    ["⚙️","Procesador","MediaTek Dimensity 9400"],
    ["💾","RAM","8GB (Física)"],
    ["💾","Almacenamiento","256GB (UFS 4.0)"],
    ["📷","Cámara principal","50MP (Sensor 1) + 50MP (Periscopio 5x) + 50MP"],
    ["📷","Cámara frontal","50MP (Eye Tracking AF)"],
    ["🔋","Batería","5500mAh / Carga rápida 100W + Inalámbrica"],
    ["🔥","Sistema operativo","Android 15 + HiOS 15"],
    ["✅","Lector de Huella","Ultrasónico en pantalla"],
    ["💦","Resistencia","IP68 (Sumergible)"],
    ["✨","Diseño","Borde infinito con marco de aleación"],
    ["🌀","Ella AI","IA Multimodal avanzada"],
  ],
};
